packages:
  - "packages/*"
  - "apps/*"
  - "tools/*"

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  libxmljs2: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  autocannon>hyperid: ^4.0.0

peerDependencyRules:
  ignoreMissing:
    - "@napi-rs/wasm-runtime"
