apiVersion: v1
kind: Service
metadata:
  name: origin-loom-operations
  labels:
    app: origin-loom
spec:
  type: ClusterIP
  selector:
    app: origin-loom
  ports:
    - name: operations
      port: 9090
      targetPort: metrics
