apiVersion: v1
kind: Service
metadata:
  name: ssr-kit
  labels:
    app: ssr-kit
spec:
  type: ClusterIP
  selector:
    app: ssr-kit
  ports:
    - name: http
      port: 3005
      targetPort: 3005
