import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname, "../..");
const generateIcons = createRequire(import.meta.url).resolve(
  "@originloom/tooling/bin/generate-icons.mjs",
);

describe("generate-icons", () => {
  it("produces TSX components and barrel exports from SVG sources", () => {
    execFileSync(process.execPath, [generateIcons], {
      cwd: ROOT,
      env: { ...process.env, ORIGIN_APP_ROOT: ROOT },
      stdio: "pipe",
    });

    const componentPath = join(ROOT, "src/components/icons/brand-mark.tsx");
    const indexPath = join(ROOT, "src/components/icons/index.ts");

    expect(existsSync(componentPath)).toBe(true);
    expect(readFileSync(componentPath, "utf8")).toContain("Generated by npm run icons");
    expect(readFileSync(componentPath, "utf8")).toContain("currentColor");
    expect(readFileSync(componentPath, "utf8")).not.toMatch(/#[0-9a-f]{3,8}/i);
    expect(readFileSync(indexPath, "utf8")).toContain("BrandMark");
  });
});
