import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname, "../..");

describe("generate-icons", () => {
  it("produces TSX components and barrel exports from SVG sources", () => {
    execFileSync(process.execPath, [join(ROOT, "scripts/generate-icons.mjs")], {
      cwd: ROOT,
      stdio: "pipe",
    });

    const componentPath = join(ROOT, "src/components/icons/brand-mark.tsx");
    const indexPath = join(ROOT, "src/components/icons/index.ts");

    expect(existsSync(componentPath)).toBe(true);
    expect(readFileSync(componentPath, "utf8")).toContain("Generated by npm run icons");
    expect(readFileSync(indexPath, "utf8")).toContain("BrandMark");
  });
});
