#!/usr/bin/env node
/**
 * SVG → React TSX codegen.
 * Kaynak: src/assets/svg/*.svg
 * Çıktı:  src/components/icons/*.tsx + index.ts
 */
import { execFileSync } from "node:child_process";
import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SVG_DIR = join(ROOT, "src/assets/svg");
const OUT_DIR = join(ROOT, "src/components/icons");
const BANNER = "// Generated by npm run icons — do not edit.\n";

function toPascalCase(kebab) {
  return kebab
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function svgStem(filename) {
  return basename(filename, ".svg");
}

async function listSvgFiles() {
  let entries;
  try {
    entries = await readdir(SVG_DIR);
  } catch (err) {
    if (err && typeof err === "object" && "code" in err && err.code === "ENOENT") {
      return [];
    }
    throw err;
  }
  return entries.filter((name) => name.endsWith(".svg")).sort();
}

async function removeStaleOutputs(svgFiles) {
  const expected = new Set(svgFiles.map((name) => `${svgStem(name)}.tsx`));
  let outputs;
  try {
    outputs = await readdir(OUT_DIR);
  } catch (err) {
    if (err && typeof err === "object" && "code" in err && err.code === "ENOENT") {
      return;
    }
    throw err;
  }

  await Promise.all(
    outputs
      .filter((name) => name.endsWith(".tsx") && !expected.has(name))
      .map((name) => rm(join(OUT_DIR, name))),
  );
}

async function runSvgr(svgFiles) {
  if (svgFiles.length === 0) {
    await writeFile(join(OUT_DIR, "index.ts"), `${BANNER}// No SVG sources in src/assets/svg\n`);
    return;
  }

  const svgrBin = join(ROOT, "node_modules/@svgr/cli/bin/svgr");
  execFileSync(
    process.execPath,
    [
      svgrBin,
      "--config-file",
      join(ROOT, ".svgrrc.cjs"),
      "--out-dir",
      OUT_DIR,
      "--filename-case",
      "kebab",
      "--ext",
      "tsx",
      "--no-index",
      SVG_DIR,
    ],
    { cwd: ROOT, stdio: "inherit" },
  );
}

async function stampGeneratedFiles(svgFiles) {
  await Promise.all(
    svgFiles.map(async (name) => {
      const outPath = join(OUT_DIR, `${svgStem(name)}.tsx`);
      const body = await readFile(outPath, "utf8");
      if (!body.startsWith(BANNER)) {
        await writeFile(outPath, `${BANNER}${body}`);
      }
    }),
  );
}

async function writeBarrel(svgFiles) {
  const lines = svgFiles.map((name) => {
    const stem = svgStem(name);
    const exportName = toPascalCase(stem);
    return `export { default as ${exportName} } from "./${stem}";`;
  });

  const content =
    lines.length > 0
      ? `${BANNER}${lines.join("\n")}\n`
      : `${BANNER}// No SVG sources in src/assets/svg\n`;

  await writeFile(join(OUT_DIR, "index.ts"), content);
}

function formatOutputs() {
  const prettierBin = join(ROOT, "node_modules/prettier/bin/prettier.cjs");
  execFileSync(process.execPath, [prettierBin, "--write", OUT_DIR], {
    cwd: ROOT,
    stdio: "ignore",
  });
}

async function main() {
  const svgFiles = await listSvgFiles();
  await removeStaleOutputs(svgFiles);
  await runSvgr(svgFiles);
  await stampGeneratedFiles(svgFiles);
  await writeBarrel(svgFiles);
  formatOutputs();

  const count = svgFiles.length;
  console.log(`[icons] ${count} SVG → ${count} TSX (${OUT_DIR})`);
}

main().catch((err) => {
  console.error("[icons] failed:", err);
  process.exit(1);
});
