apiVersion: v1
kind: Service
metadata:
  name: origin-loom
  labels:
    app: origin-loom
spec:
  type: ClusterIP
  selector:
    app: origin-loom
  ports:
    - name: http
      port: 3005
      targetPort: 3005
