// Generated by npm run icons — do not edit.
import type { SVGProps } from "react";
const SvgBrandMark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 32 32" width="1em" height="1em" {...props}><path fillRule="evenodd" d="M8 4h16a4 4 0 0 1 4 4v16a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V8a4 4 0 0 1 4-4m2 8v8h3v-3h6v3h3v-8h-3v3h-6v-3z" clipRule="evenodd" /></svg>;
export default SvgBrandMark;